### PR TITLE
fix: Improved isAxiosHeaders validation to handle obfuscated code

### LINKED ISSUE #59: Response headers aren't being converted for axios 1.x
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I wanted to bring to your attention an issue I encountered while working on a project that involves updating `axios` from version `0.24.0` to `1.x` and `axios-case-converter` from version `0.9.0` to `1.1.0`.

After the update, I observed a problem related to response headers case conversion. After some debugging, I narrowed down the issue to the `overwriteHeadersOrNoop` function, particularly the validation within it:

```ts
if (
    options?.ignoreHeaders ||
    (!isPlainObject(headers) && !isAxiosHeaders(headers))
)
```

Upon investigation, it seems that the problem arises when the project is deployed, involving bundling, minification, and obfuscation. The `isAxiosHeaders(headers)` validation fails, even though the headers are, in fact, of type `AxiosHeaders`. This occurs because the validation relies on checking the constructor name.

Is there a reason for the use of the constructor name instead of validating whether it is an instance of `AxiosHeaders`?

To confirm this behavior, I made a patch to the `axios-case-converter@1.1.0` and added some log statements to the code:

```ts
import { AxiosHeaders } from "axios";

...

const overwriteHeadersOrNoop = (
    ...
): void => {
    console.log(
        `isPlainObject: ${isPlainObject(headers)},
         isAxiosHeaders: ${isAxiosHeaders(headers)},
         instanceof: ${headers instanceof AxiosHeaders}
    `);
}
```

When running the code locally, the logs showed the expected results. However, after deployment, the logs indicated that `isAxiosHeaders(headers)` was returning `false`, even though `headers instanceof AxiosHeaders` was `true`.

Local Logs:
local

Deployed Logs:
docker-compose

It appears that the issue might be related to the obfuscation process affecting the constructor name comparison.

For additional context, here is the configuration for the Axios instance and the relevant request:

**Axios Instance:**

```ts
const axiosInstance = applyConverters(
  axios.create({
    baseURL: SOME_URL,
    timeout: 10000,
    paramsSerializer: (params) => stringify(params, { arrayFormat: 'repeat' }),
  })
);
```

**Request:**

```ts
axiosInstance.post(SOME_URL, formData, {
  headers: {
    'Content-Type': 'multipart/form-data',
  },
});
```

**On Success:**
```ts
const something = data.headers.contentLocation;  // Fails due to incorrect case conversion
```

If you need any more details or if there's anything else I can do to assist in the resolution process, please let me know.

Thank you for your time and attention to this matter.

### PR DESCRIPTION
**Pull request by joaolrpm**
Fixes #59 

However, I've encountered an issue with the UMD build due to axios imports after modifying `util.ts`. To fix it, I added `browser: true` to the `nodeResolve` in `rollup.config.js`. Since I'm not well-versed in rollup configuration, could you provide guidance on the best way to proceed in this situation?

image

### CODE REVIEW

File: src/util.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import { Transformable, TransformableObject } from './types';
+import { AxiosHeaders } from 'axios';
```
Comment (mpyw) [inline src/util.ts:2]: It seems that `AxiosHeaders` can be imported in the latest version. thank you

**Comment by joaolrpm** [comment]
Hi @mpyw 👋

I apologize for any inconvenience caused. The release wasn't published as it seems to have failed in the UMD build. I'll open a proposal PR to address this situation soon.
